# Generated by Django 4.0.5 on 2022-06-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Pages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Publication',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='PublicationDate',
            field=models.DateField(null=True),
        ),
    ]
