# Generated by Django 4.0.5 on 2022-06-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_pages_books_publication_books_publicationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Pages',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Publication',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='PublicationDate',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Title',
            new_name='title',
        ),
    ]
