# Generated by Django 4.0.5 on 2022-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_books_author_rename_pages_books_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
