# Generated by Django 4.0.5 on 2022-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='book_image'),
        ),
    ]
