# Generated by Django 4.0.5 on 2022-06-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='images',
        ),
    ]
